# ~/.config/chromium-flags.conf

# Run on Wayland
--ozone-platform-hint=auto
--ozone-platform=wayland

# Input method (Fcitx5) on Wayland
--enable-wayland-ime
--wayland-text-input-version=3

# ALL Enabled features
# 1. Touchpad gestures
# 2. Hardware video acceleration
--enable-features=TouchpadOverscrollHistoryNavigation,AcceleratedVideoDecodeLinuxGL
