bind = ALT, F4, killactive
bind = WIN, F4, exit

bind = SHIFT, F10, exec, uwsm-app -T
bind = SHIFT, F11, exec, uwsm-app -T -- python3

bind = WIN, E, exec, uwsm-app -- $fileManager
//bind = WIN, L, exec, uwsm-app -- hyprlock
bind = WIN, L, exec, loginctl lock-session

bind = WIN + CTRL, left, workspace, -1
bind = WIN + CTRL, right, workspace, +1

bind = WIN + SHIFT, left, movetoworkspace, -1
bind = WIN + SHIFT, right, movetoworkspace, +1

bind = WIN + ALT, left, movetoworkspacesilent, -1
bind = WIN + ALT, right, movetoworkspacesilent, +1

bind = WIN, P, pseudo # dwindle
bind = WIN, J, layoutmsg, togglesplit # dwindle
bind = WIN, F, togglefloating

bind = , F11, fullscreen, 0
bind = ALT , F11, fullscreen, 1

bind = WIN, left, movewindow, l
bind = WIN, right, movewindow, r
bind = WIN, up, movewindow, u
bind = WIN, down, movewindow, d

bind = ALT, Tab, cyclenext
bind = SHIFT + ALT, Tab, cyclenext, prev

# Laptop multimedia keys for volume and LCD brightness
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1dB
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1dB
bindel = SHIFT, XF86AudioRaiseVolume, exec, pactl set-source-volume @DEFAULT_SOURCE@ +1dB
bindel = SHIFT, XF86AudioLowerVolume, exec, pactl set-source-volume @DEFAULT_SOURCE@ -1dB
bindel = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindel = SHIFT, XF86AudioMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Multimedia (playerctl)
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Quick menu (rofi)
bind = WIN, V, exec, cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
bind = WIN, R, exec, rofi -show drun -config "app"
bind = WIN, X, exec, rofi -show Power -modes "Power:~/.config/rofi/power.sh"

# Status bar (Quickshell)
bindr = SUPER, SUPER_L, exec, qs ipc call root toggleOverlay
bind = SUPER, H, exec, qs ipc call root toggleVisibility

# Screenshot (grim & slurp)
bind = , Print, exec, grim - | wl-copy
bind = CTRL, Print, exec, grim -g "$(slurp -d)" - | wl-copy
bind = ALT, Print, exec, hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - - | wl-copy

# Mouse
bindm = WIN, mouse:272, movewindow
bind = WIN, mouse_up, workspace, +1
bind = WIN, mouse_down, workspace, -1

# Gestures
gesture = 4, horizontal, workspace
