$SURFACE = rgb(edf3f7)
$ON-SURFACE = rgb(080808)

$SURFACE-CONTAINER = rgb(e6ecf0)
$ON-SURFACE-CONTAINER = rgb(0e0f0f)

$PRIMARY = rgb(86b5d3)
$ON-PRIMARY = rgb(1c262c)

$SECONDARY = rgb(9baebc)
$ON-SECONDARY = rgb(373e43)
