# Graphics environment variables

# Hardware video acceleration (Auto-handled)
#env = LIBVA_DRIVER_NAME, iHD
#env = LIBVA_DRIVER_NAME, nvidia
#env = VDPAU_DRIVER, nvidia
#env = VDPAU_DRIVER, va_gl

# OpenGL & Vulkan
#env = _EGL_VENDOR_LIBRARY_FILENAMES, /usr/share/glvnd/egl_vendor.d/50_mesa.json
#env = _EGL_VENDOR_LIBRARY_FILENAMES, /usr/share/glvnd/egl_vendor.d/10_nvidia.json
#env = __GLX_VENDOR_LIBRARY_NAME, mesa
#env = __GLX_VENDOR_LIBRARY_NAME, nvidia
#env = MESA_VK_DEVICE_SELECT, 8086:9a68
#env = MESA_VK_DEVICE_SELECT, 10de:25a2

# NVIDIA Optimus
# May use prime-run to run apps instead
#env = __NV_PRIME_RENDER_OFFLOAD, 1

# Hyprland grpahic cards priority (High to low)
# *** SWITCHED TO .bashrc ***
# Intel only (NOT outputing HDMI monitor signal)
#env = AQ_DRM_DEVICES, /dev/dri/card1
# Intel first
#env = AQ_DRM_DEVICES, /dev/dri/card1:/dev/dri/card0
# Nvidia first
#env = AQ_DRM_DEVICES, /dev/dri/card0:/dev/dri/card1
