general {
    lock_cmd = qs ipc call lock triggerLock && pidof qs quickshell hyprlock || hyprlock
    before_sleep_cmd = hyprctl repl "save_monitors_dpms(false)" && loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl repl "restore_monitors_dpms()"  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 180
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}

listener {
    timeout = 240
    on-timeout = hyprctl repl "save_monitors_dpms(false)"
    on-resume = hyprctl repl "restore_monitors_dpms()"
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
