background {
    path = ~/.config/hypr/bg/desktop.png

    blur_passes = 3
    blur_size = 10

    brightness = 0.8
}

input-field {
    size = 300, 50

    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false

    outline_thickness = 0
    outer_color = rgba(edf3f799)
    check_color = rgba(edf3f799)
    fail_color = rgba(edf3f799)
    inner_color = rgba(edf3f799)


    font_color = rgb(080808)
    font_family = monospace bold

    shadow_passes = 2
    shadow_size = 10

    fade_on_empty = false
    placeholder_text =  $USER

    hide_input = false
    rounding = -1

    fail_text = $FAIL
    fail_transition = 300

    swap_font_color = false

    position = 0,100
    halign = center
    valign = bottom
}

label {
    text = $TIME
    color = rgba(edf3f799)
    font_size = 96
    font_family = monospace bold ultra-condensed

    shadow_size = 10
    shadow_passes = 2


    position = 0, -120
    halign = center
    valign = top
}

label {
    text = cmd[update:1000] date "+%Y.%m.%d %a"
    color = rgba(edf3f799)
    font_size = 18
    font_family = monospace bold ultra-condensed

    shadow_size = 10
    shadow_passes = 2

    position = 0, -280
    halign = center
    valign = top
}
